# Generated by Django 5.0.3 on 2024-03-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Earrings'), ('2', 'Necklaces'), ('3', 'Handles')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
