# Generated by Django 5.0.2 on 2024-04-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewel', '0002_remove_product_categories_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Bracelets'), ('2', 'Necklaces'), ('3', 'Earrings')], max_length=1),
        ),
    ]
