# Generated by Django 5.0.2 on 2024-04-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewel', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Bracelets'), ('2', 'Necklaces'), ('3', 'Earrings'), ('4', 'Rings')], max_length=1),
        ),
    ]
